name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Every day at midnight
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - flutter_version: dev
            allow_failure: true
          - flutter_version: beta
            allow_failure: true
          - flutter_version: stable
            allow_failure: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ matrix.flutter_version }}
      - run: flutter pub get
      - run: flutter format --set-exit-if-changed .
        continue-on-error: ${{ matrix.allow_failure }}
      - run: flutter analyze
        continue-on-error: ${{ matrix.allow_failure }}
      - run: flutter test
        continue-on-error: ${{ matrix.allow_failure }}
